# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: bba683d69dd4e8b993804124156557cc4bcccef0526b9926b6df86e0d6fcddd69ac66068465dde97be879cf306376fa7c2b8538fddf836dffb4cf3919d4c131b

test:
  secret_key_base: ad1e88d06f4734b5780be74893497ac251436ae8f5d34f61402cee250336e940f3e24b756429c862e73b65c716040179c23dc372f8fd85df3e18ad9de5cbe951

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
